### ISSUE TITLE
这个程序怎么跑呢

### ISSUE THREAD

**Issue by goalong** [SmileXie/zhihu_bigdata#2]
当前的代码能直接运行吗，我在本地执行了一下，from enum import Enum这个无法找到，就先注释掉了，然后再运行，显示fail to login，登陆不成功，是需要什么步骤或者配置吗？

**Comment by SmileXie** [comment]
可以直接跑。
from enum import Enum找不到的原因你上网查一下，我的环境中没有出现。

还要把下面的_phone_num和_password改成你自己的手机号、密码才可以登录。
`
class ZhihuCrawler(object):

```
def __init__(self):
    self._base_url = r"https://www.zhihu.com"
    self._phone_num = r""
    self._password = r""`
```

**Comment by goalong** [comment]
@SmileXie Enum这个是python3.4新添加的，我在python2.7.10下跑有好几处报错，你是在python3下面跑的吗？另外建议添加一个使用说明，只是简单写几个步骤介绍一下如何使用这个代码。

**Comment by gunerguner** [comment]
@goalong 在2.7版本下会有很多问题，不仅仅是lib的缺失，包括很多库函数的参数不同。
在python 3.5下可以正常运行。
login问题需要自己在代码中填入用户名和密码，作者默认使用手机号登录，有一个pull request解决的是这个问题。（本来我想自己提交了，后来看到有人已经做了）。
@SmileXie

**Comment by SmileXie** [comment]
@gunerguner 解释得很清楚了，说得很好。
pull request我这两天会处理
